export const DEFAULT_TERMS = [
  { source: 'Outcomes-not-outputs', target: '重结果，而非过程产出' },
  { source: 'Agent Suitability Framework', target: '智能体适用性评估框架' },
  { source: 'Double Diamond Methodology', target: '双钻设计方法论' },
  { source: 'Agent Design Card', target: '智能体设计卡' },
  { source: 'Agent Architecture Design Language', target: '智能体架构设计语言' },
  { source: 'Brownfield Integrations', target: '棕地集成' },
  { source: 'Low-code vs Pro-code', target: '低代码与专业代码' },
  { source: 'Model Context Protocol', target: '模型上下文协议' },
  { source: 'Agent-to-Agent Protocol', target: '智能体对智能体协议' },
  { source: 'Single Agent', target: '单智能体' },
  { source: 'Constrained Agent', target: '受限智能体' },
  { source: 'Deep Agent', target: '深度智能体' },
  { source: 'Autonomous Agent', target: '自主智能体' },
  { source: 'Agent-assisted', target: '智能体辅助' },
  { source: 'Human-in-the-loop', target: '人在回路中' },
  { source: 'Human-on-the-loop', target: '人在线监控' },
  { source: 'Human-out-of-the-loop', target: '人不在回路中' },
  { source: 'Enterprise Orchestration', target: '企业级编排' },
  { source: 'Domain Orchestration', target: '领域级编排' },
  { source: 'Retrieval-Augmented Generation', target: '检索增强生成' },
  { source: 'Short-term Memory', target: '短期记忆' },
  { source: 'Long-term Memory', target: '长期记忆' },
  { source: 'Semantic Memory', target: '语义记忆' },
  { source: 'Procedural Memory', target: '程序记忆' },
  { source: 'Episodic Memory', target: '情境记忆' },
  { source: 'Semantic Search', target: '语义搜索' },
  { source: 'Hybrid Search', target: '混合搜索' },
  { source: 'Model Routing', target: '模型路由' },
  { source: 'Golden Dataset', target: '黄金数据集' },
  { source: 'Ground Truth', target: '基准真相' },
  { source: 'LLM-as-judge', target: '大模型作为裁判' },
  { source: 'F1 score', target: 'F1分值' },
  { source: 'Trace logs', target: '链路追踪日志' },
  { source: 'Telemetry', target: '遥测数据' },
  { source: 'Acceptance Environment', target: '测试验收环境' },
  { source: 'Silent Failure', target: '静默失败' },
  { source: 'Task Drift', target: '任务漂移' },
  { source: 'Cross-Prompt Injection Attacks', target: '跨站提示词注入攻击' },
  { source: 'PII masking', target: '个人隐私敏感信息脱敏遮蔽' },
  { source: 'Inference-layer guardrails', target: '推理层安全护栏' },
  { source: 'Security Operations Center', target: '安全运营中心' },
  { source: 'Security Information & Event', target: '安全信息和事件管理' },
  { source: 'Secure Access Service Edge', target: '安全访问服务边缘' },
] as const;
